apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ lower .Chart.Name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 1 }}
  selector:
    matchLabels:
      app: {{ lower .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ lower .Chart.Name }}
    spec:
      containers:
      - name: {{ lower .Chart.Name }}
        image: {{ .Values.image }}:{{ .Chart.AppVersion }} # This is auto updated by the release mechanism
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort | default 8080 }}
        {{ if or (.Values.secretVars) (.Values.envVars) -}}
        env:
        {{- range $secret, $value := .Values.secretVars }}
        - name: {{ $secret }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Chart.Name }}-secrets
              key: {{ $secret }}
        {{- end}}
        {{- range $var, $value := .Values.envVars }}
        - name: {{ $var }}
          value: {{ quote $value }}
        {{ end -}}
        {{ end -}}
        {{- if .Values.volumeMounts -}}
        volumeMounts:
        {{- range $volume := .Values.volumeMounts }}
          - mountPath: {{ $volume.mountPath }}
            name: {{ $volume.name }}
            readOnly: {{ $volume.readOnly | default "true" }}
        {{- end }}
        {{- end }}
      {{- if .Values.volumeMounts }}
      volumes:
      {{- range $volume := .Values.volumeMounts }}
        - name: {{ $volume.name }}
        {{- toYaml $volume.source | nindent 10}}
      {{- end }}
      {{- end }}