---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Chart.Name }}-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-sdk
  data:
    {{- range $v := .Values.secrets }}
    - secretKey: {{lower $v.name | replace "_" "-"}}
      remoteRef:
        key: {{$v.path}}
    {{- end }}