{{if .Values.secretVars }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}-secrets
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretStoreName | default "1password-sdk" }}
  data:
    {{- range $secret, $value := .Values.secretVars }}
    - secretKey: {{ $secret }}
      remoteRef:
        key: {{ (split "/" (lower $value))._0 }}
        property: {{ (split "/" (lower $value))._1 }}
    {{ end -}}
{{ end }}