apiVersion: v2
name: sexybabeycord
description: The magical multitool of the century
type: application
version: 0.6.4
appVersion: "0.6.4"
dependencies:
  - name: single-container
    version: "1.x.x"
    repository: "oci://ghcr.io/vaughnw128/charts"
