name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  create-tag:
    name: "Create Git Tag"
    runs-on: "ubuntu-latest"
    needs: test
    outputs:
      tag: ${{ steps.get-tag.outputs.PKG_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Get Poetry Version
        id: "get-tag"
        shell: "bash"
        run: |
          echo PKG_VERSION=$(poetry version --short) >> $GITHUB_OUTPUT

      - name: Set Tag
        id: git-tag
        shell: "bash"
        run: |
          git tag v${{ steps.get-tag.outputs.PKG_VERSION }} && git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=ghcr.io/vaughnw128/sexybabeycord:${{ needs.create-tag.outputs.tag }}
          cache-to: type=inline
          tags: |
            ghcr.io/vaughnw128/sexybabeycord:${{ needs.create-tag.outputs.tag }}
          build-args: |
            git_sha=${{ github.sha }}

  release:
    name: "Release to Immanent Grove"
    runs-on: ubuntu-latest
    needs:
      - build
      - create-tag
    steps:
      - name: Open Immanent Grove PR
        env:
          ENV_REPO: ${{ github.event.repository.owner.name }}/immanent-grove
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: application-update.yml
          repo: ${{ env.ENV_REPO }}
          token: ${{ secrets.RELEASE_TOKEN }}
          inputs: '{"tag_name": "${{ needs.create-tag.outputs.tag }}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ github.event.repository.full_name }}:${{ needs.create-tag.outputs.tag }}"}'
          ref: refs/heads/main