name: Build and Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: "Build Image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          cache-from: type=registry,ref=ghcr.io/vaughnw128/sexybabeycord:${{github.ref_name}}
          cache-to: type=inline
          tags: |
            ghcr.io/vaughnw128/sexybabeycord:${{github.ref_name}}
          build-args: |
            git_sha=${{ github.sha }}

  release:
    name: "Release to Immanent Grove"
    runs-on: ubuntu-latest
    steps:
      - name: Open Immanent Grove PR
        env:
          ENV_REPO: ${{ github.event.repository.owner.name }}/immanent-grove
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: application-update.yml
          repo: ${{ env.ENV_REPO }}
          token: ${{ secrets.RELEASE_TOKEN }}
          inputs: '{"tag_name": "${{github.ref_name}}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ github.event.repository.full_name }}:${{github.ref_name}}"}'
          ref: refs/heads/main