name: Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write
  actions: read

jobs:
  release:
    if: ${{ github.event_name != 'push' || !contains(github.event.head_commit.message, '[no ci]') }}
    uses: vaughnw128/hakoniwa/.github/workflows/release.yml@main
    with:
      language: python
      helm-path: ./helm
    secrets: inherit
