on:
  workflow_call

jobs:
  release:
    name: "Release to Immanent Grove Environment"
    runs-on: ubuntu-latest
    steps:
      - name: Open PR in Environment Repository for new App Version
        env:
          ENV_REPO: ${{ github.event.repository.owner.name }}/immanent-grove
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: application-update.yml
          repo: ${{ env.ENV_REPO }}
          token: ${{ secrets.RELEASE_TOKEN }}
          inputs: '{"tag_name": "${GITHUB_REF##*/}", "app_repo": "${{ github.event.repository.name }}", "image": "${{ github.event.repository.full_name }}:${GITHUB_REF##*/}"}'
          ref: refs/heads/main
