name: Security

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1"

permissions:
  contents: read
  issues: write
  security-events: write

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      issues: write
    uses: vaughnw128/hakoniwa/.github/workflows/code-scanning.yml@main
    with:
      language: python
    secrets: inherit
