name: "Tag"

on:
  workflow_call

jobs:
  create-tag:
    name: "Create Git Tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Get Poetry Version
        id: "get-tag"
        shell: "bash"
        run: |
          echo PKG_VERSION=$(poetry version --short) >> $GITHUB_OUTPUT

      - name: Set Tag
        shell: "bash"
        run: |
          git tag v${{ steps.get-tag.outputs.PKG_VERSION }} && git push --tags