name: Code Quality & Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  test:
    uses: vaughnw128/hakoniwa/.github/workflows/test.yml@main
    with:
      language: python
      python-version: "3.12"
      helm-path: ./helm
