name: Verify PR

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  verify:
    uses: vaughnw128/hakoniwa/.github/workflows/verify-pr.yml@main
    with:
      pr-title: ${{ github.event.pull_request.title }}
