name: Verify

on:
  pull_request:
  push:
    branches: [main]

jobs:
  verify:
    uses: vaughnw128/hakoniwa/.github/workflows/verify.yml@main
    with:
      language: python
      helm-path: ./helm
      secrets: inherit
