name: Verify

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write
  packages: read

jobs:
  verify:
    uses: vaughnw128/hakoniwa/.github/workflows/verify.yml@main
    with:
      language: python
      helm-path: ./helm
      python-version: "3.14"
    secrets: inherit
